"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "[▌](blue) $username$directory$git_branch$git_status$character"
right_format = ""

palette = 'zenbones_light'

[palettes.zenbones_light]
rosewater = "#ab6b58"
flamingo = "#b47b70"
pink = "#995d8c"
mauve = "#88507d"
red = "#a8334c"
maroon = "#94253e"
peach = "#944927"
yellow = "#803d1c"
green = "#4f6c31"
teal = "#3f5a22"
sky = "#3b8992"
sapphire = "#2b747c"
blue = "#286486"
lavender = "#1d5573"
text = "#2c363c"
subtext1 = "#4f5e68"
subtext0 = "#63717a"
overlay2 = "#78838b"
overlay1 = "#948b85"
overlay0 = "#b5a7a0"
surface2 = "#c4b8b1"
surface1 = "#cfc1ba"
surface0 = "#dfd9d6"
base = "#f0edec"
mantle = "#e6e1df"
crust = "#e8e4e3"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false
style_user = "fg:overlay1"
style_root = "fg:red"
format = '[$user@]($style)'

[directory]
style = "fg:text"
format = "[$path]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "fg:blue"
format = ' [$symbol $branch]($style)'

[git_status]
style = "fg:teal"
format = ' [$all_status$ahead_behind]($style)'

[character]
success_symbol = '[ ❯ ](fg:teal)'
error_symbol = '[ ❯ ](fg:red)'
vimcmd_symbol = '[ ❮ ](fg:blue)'

[status]
disabled = false
style = 'fg:overlay1'
failure_style = 'fg:red'
success_style = 'fg:green'
success_symbol = ""
symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = ""
format = '[$symbol $status ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "fg:overlay1"
format = '[ $time]($style)'
