"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "[█](surface0)$os$username[](bg:blue fg:surface0)$directory[](fg:blue bg:green)$git_branch$git_status[](fg:green) "
right_format = "[](fg:surface0)$status[](bg:surface0 fg:text)$time"

palette = 'everforest_dark'

[palettes.everforest_dark]
rosewater = "#e69875"
flamingo = "#e67e80"
pink = "#d699b6"
mauve = "#bb8aac"
red = "#ef7b83"
maroon = "#c56b73"
peach = "#e29a73"
yellow = "#dbbc7f"
green = "#a7c080"
teal = "#83c092"
sky = "#91c8c1"
sapphire = "#6caaa4"
blue = "#7fbbb3"
lavender = "#a9a6c2"
text = "#d3c6aa"
subtext1 = "#c4bba4"
subtext0 = "#9da9a0"
overlay2 = "#859289"
overlay1 = "#7a8478"
overlay0 = "#687a74"
surface2 = "#495156"
surface1 = "#414b50"
surface0 = "#374145"
base = "#272e33"
mantle = "#2e383c"
crust = "#1e2326"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:blue"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[status]
disabled = false
style = 'bg:surface0'
failure_style = 'bg:surface0 fg:red'
success_style = 'bg:surface0 fg:green'
success_symbol = ""
symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = ""
format = '[ $symbol $status ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:blue"
format = '[[  $time ](fg:text bg:surface0)]($style)'
