"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "[█](surface0)$os$username[](bg:blue fg:surface0)$directory[](fg:blue bg:green)$git_branch$git_status[](fg:green) "
right_format = "[](fg:surface0)$status[](bg:surface0 fg:text)$time"

palette = 'tokyonight_moon'

[palettes.tokyonight_moon]
rosewater = "#fca7ea"
flamingo = "#c099ff"
pink = "#ff007c"
mauve = "#b4f9f8"
red = "#ff757f"
maroon = "#c53b53"
peach = "#ff966c"
yellow = "#ffc777"
green = "#c3e88d"
teal = "#4fd6be"
sky = "#86e1fc"
sapphire = "#65bcff"
blue = "#82aaff"
lavender = "#89ddff"
text = "#c8d3f5"
subtext1 = "#737aa2"
subtext0 = "#828bb8"
overlay2 = "#636da6"
overlay1 = "#545c7e"
overlay0 = "#444a73"
surface2 = "#3b4261"
surface1 = "#394b70"
surface0 = "#2d3f76"
base = "#222436"
mantle = "#1e2030"
crust = "#191B29"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:blue"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[status]
disabled = false
style = 'bg:surface0'
failure_style = 'bg:surface0 fg:red'
success_style = 'bg:surface0 fg:green'
success_symbol = ""
symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = ""
format = '[ $symbol $status ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:blue"
format = '[[  $time ](fg:text bg:surface0)]($style)'
