# Theme: Rosé Pine Main
# Source palette: https://github.com/rose-pine/neovim/blob/main/lua/rose-pine/palette.lua

theme[main_bg]="#191724"
theme[main_fg]="#e0def4"
theme[title]="#e0def4"
theme[hi_fg]="#ebbcba"
theme[selected_bg]="#403d52"
theme[selected_fg]="#9ccfd8"
theme[inactive_fg]="#6e6a86"
theme[graph_text]="#e0def4"
theme[meter_bg]="#26233a"
theme[proc_misc]="#ebbcba"

theme[cpu_box]="#c4a7e7"
theme[mem_box]="#95b1ac"
theme[net_box]="#31748f"
theme[proc_box]="#9ccfd8"
theme[div_line]="#6e6a86"

theme[temp_start]="#95b1ac"
theme[temp_mid]="#f6c177"
theme[temp_end]="#eb6f92"

theme[cpu_start]="#31748f"
theme[cpu_mid]="#9ccfd8"
theme[cpu_end]="#c4a7e7"

theme[free_start]="#c4a7e7"
theme[free_mid]="#9ccfd8"
theme[free_end]="#31748f"

theme[cached_start]="#31748f"
theme[cached_mid]="#9ccfd8"
theme[cached_end]="#c4a7e7"

theme[available_start]="#f6c177"
theme[available_mid]="#ebbcba"
theme[available_end]="#eb6f92"

theme[used_start]="#95b1ac"
theme[used_mid]="#31748f"
theme[used_end]="#9ccfd8"

theme[download_start]="#f6c177"
theme[download_mid]="#ebbcba"
theme[download_end]="#eb6f92"

theme[upload_start]="#95b1ac"
theme[upload_mid]="#31748f"
theme[upload_end]="#9ccfd8"
