# Theme: Rosé Pine Dawn
# Source palette: https://github.com/rose-pine/neovim/blob/main/lua/rose-pine/palette.lua

theme[main_bg]="#faf4ed"
theme[main_fg]="#575279"
theme[title]="#575279"
theme[hi_fg]="#d7827e"
theme[selected_bg]="#dfdad9"
theme[selected_fg]="#286983"
theme[inactive_fg]="#9893a5"
theme[graph_text]="#575279"
theme[meter_bg]="#f2e9e1"
theme[proc_misc]="#286983"

theme[cpu_box]="#907aa9"
theme[mem_box]="#6d8f89"
theme[net_box]="#286983"
theme[proc_box]="#56949f"
theme[div_line]="#9893a5"

theme[temp_start]="#6d8f89"
theme[temp_mid]="#ea9d34"
theme[temp_end]="#b4637a"

theme[cpu_start]="#286983"
theme[cpu_mid]="#56949f"
theme[cpu_end]="#907aa9"

theme[free_start]="#907aa9"
theme[free_mid]="#56949f"
theme[free_end]="#286983"

theme[cached_start]="#286983"
theme[cached_mid]="#56949f"
theme[cached_end]="#907aa9"

theme[available_start]="#ea9d34"
theme[available_mid]="#d7827e"
theme[available_end]="#b4637a"

theme[used_start]="#6d8f89"
theme[used_mid]="#286983"
theme[used_end]="#56949f"

theme[download_start]="#ea9d34"
theme[download_mid]="#d7827e"
theme[download_end]="#b4637a"

theme[upload_start]="#6d8f89"
theme[upload_mid]="#286983"
theme[upload_end]="#56949f"
