# Theme: Tokyo Night Moon
# Source: https://github.com/folke/tokyonight.nvim/tree/main/extras/btop

theme[main_bg]="#222436"
theme[main_fg]="#c8d3f5"
theme[title]="#c8d3f5"
theme[hi_fg]="#ff966c"
theme[selected_bg]="#2f334d"
theme[selected_fg]="#86e1fc"
theme[inactive_fg]="#545c7e"
theme[graph_text]="#c8d3f5"
theme[meter_bg]="#3b4261"
theme[proc_misc]="#86e1fc"

theme[cpu_box]="#589ed7"
theme[mem_box]="#589ed7"
theme[net_box]="#589ed7"
theme[proc_box]="#589ed7"
theme[div_line]="#589ed7"

theme[temp_start]="#c3e88d"
theme[temp_mid]="#ffc777"
theme[temp_end]="#ff757f"

theme[cpu_start]="#c3e88d"
theme[cpu_mid]="#ffc777"
theme[cpu_end]="#ff757f"

theme[free_start]="#c3e88d"
theme[free_mid]="#ffc777"
theme[free_end]="#ff757f"

theme[cached_start]="#c3e88d"
theme[cached_mid]="#ffc777"
theme[cached_end]="#ff757f"

theme[available_start]="#c3e88d"
theme[available_mid]="#ffc777"
theme[available_end]="#ff757f"

theme[used_start]="#c3e88d"
theme[used_mid]="#ffc777"
theme[used_end]="#ff757f"

theme[download_start]="#c3e88d"
theme[download_mid]="#ffc777"
theme[download_end]="#ff757f"

theme[upload_start]="#c3e88d"
theme[upload_mid]="#ffc777"
theme[upload_end]="#ff757f"

theme[process_start]="#65bcff"
theme[process_mid]="#c099ff"
theme[process_end]="#ff007c"
