# Theme: Tokyo Night Day
# Source: https://github.com/folke/tokyonight.nvim/tree/main/extras/btop

theme[main_bg]="#e1e2e7"
theme[main_fg]="#3760bf"
theme[title]="#3760bf"
theme[hi_fg]="#b15c00"
theme[selected_bg]="#c4c8da"
theme[selected_fg]="#007197"
theme[inactive_fg]="#848cb5"
theme[graph_text]="#3760bf"
theme[meter_bg]="#c4c8da"
theme[proc_misc]="#007197"

theme[cpu_box]="#4094a3"
theme[mem_box]="#4094a3"
theme[net_box]="#4094a3"
theme[proc_box]="#4094a3"
theme[div_line]="#4094a3"

theme[temp_start]="#587539"
theme[temp_mid]="#8c6c3e"
theme[temp_end]="#f52a65"

theme[cpu_start]="#587539"
theme[cpu_mid]="#8c6c3e"
theme[cpu_end]="#f52a65"

theme[free_start]="#587539"
theme[free_mid]="#8c6c3e"
theme[free_end]="#f52a65"

theme[cached_start]="#587539"
theme[cached_mid]="#8c6c3e"
theme[cached_end]="#f52a65"

theme[available_start]="#587539"
theme[available_mid]="#8c6c3e"
theme[available_end]="#f52a65"

theme[used_start]="#587539"
theme[used_mid]="#8c6c3e"
theme[used_end]="#f52a65"

theme[download_start]="#587539"
theme[download_mid]="#8c6c3e"
theme[download_end]="#f52a65"

theme[upload_start]="#587539"
theme[upload_mid]="#8c6c3e"
theme[upload_end]="#f52a65"
